[package]
name = "bn_ate_loop"
version.workspace = true
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
ec_groups = { path = "../ec_groups" }
fq_types = { path = "../fq_types" }
schwartz_zippel = { path = "../schwartz_zippel" }

[dev-dependencies]
cairo_test.workspace = true
