[package]
name = "bn254"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
pairing = { path = "../pairing" }
fq_types = { path = "../fq_types" }
ec_groups = { path = "../ec_groups" }
bn_ate_loop = { path = "../bn_ate_loop" }
schwartz_zippel = { path = "../schwartz_zippel" }